// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api_raspi_web.Contexts;

#nullable disable

namespace api_raspi_web.Migrations
{
    [DbContext(typeof(RaspidbContext))]
    [Migration("20250705094142_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("api_raspi_web.Models.Balance", b =>
                {
                    b.Property<int>("BalanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BalanceId"));

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("BalanceId");

                    b.ToTable("Balance");

                    b.HasData(
                        new
                        {
                            BalanceId = 1,
                            Total = 15941.40m
                        },
                        new
                        {
                            BalanceId = 2,
                            Total = 3527.96m
                        },
                        new
                        {
                            BalanceId = 3,
                            Total = 2807.96m
                        });
                });

            modelBuilder.Entity("api_raspi_web.Models.CanBalance", b =>
                {
                    b.Property<int>("CanBalanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CanBalanceId"));

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("CanBalanceId");

                    b.ToTable("CanBalance");

                    b.HasData(
                        new
                        {
                            CanBalanceId = 1,
                            Total = 500m
                        },
                        new
                        {
                            CanBalanceId = 2,
                            Total = 499.99m
                        });
                });

            modelBuilder.Entity("api_raspi_web.Models.CanItem", b =>
                {
                    b.Property<int>("CanItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CanItemId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("CanItemId");

                    b.ToTable("CanItem");

                    b.HasData(
                        new
                        {
                            CanItemId = 1,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Test",
                            Price = 0.01m
                        });
                });

            modelBuilder.Entity("api_raspi_web.Models.CanTransaction", b =>
                {
                    b.Property<int>("CanTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CanTransactionId"));

                    b.Property<int>("CanBalanceId")
                        .HasColumnType("int");

                    b.Property<int>("CanItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("CanTransactionId");

                    b.HasIndex("CanBalanceId");

                    b.HasIndex("CanItemId");

                    b.ToTable("CanTransaction");

                    b.HasData(
                        new
                        {
                            CanTransactionId = 1,
                            CanBalanceId = 2,
                            CanItemId = 1,
                            TransactionDate = new DateTime(2025, 5, 17, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("api_raspi_web.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("ItemId");

                    b.ToTable("Item");

                    b.HasData(
                        new
                        {
                            ItemId = 1,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Beemden",
                            Price = 12413.44m
                        },
                        new
                        {
                            ItemId = 2,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Photographer Ksenia",
                            Price = 720.00m
                        });
                });

            modelBuilder.Entity("api_raspi_web.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<int>("BalanceId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("TransactionId");

                    b.HasIndex("BalanceId");

                    b.HasIndex("ItemId");

                    b.ToTable("Transaction");

                    b.HasData(
                        new
                        {
                            TransactionId = 1,
                            BalanceId = 2,
                            ItemId = 1,
                            TransactionDate = new DateTime(2025, 5, 17, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TransactionId = 2,
                            BalanceId = 3,
                            ItemId = 2,
                            TransactionDate = new DateTime(2025, 5, 13, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("api_raspi_web.Models.CanTransaction", b =>
                {
                    b.HasOne("api_raspi_web.Models.Balance", "CanBalance")
                        .WithMany()
                        .HasForeignKey("CanBalanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api_raspi_web.Models.Item", "CanItem")
                        .WithMany()
                        .HasForeignKey("CanItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CanBalance");

                    b.Navigation("CanItem");
                });

            modelBuilder.Entity("api_raspi_web.Models.Transaction", b =>
                {
                    b.HasOne("api_raspi_web.Models.Balance", "Balance")
                        .WithMany()
                        .HasForeignKey("BalanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api_raspi_web.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Balance");

                    b.Navigation("Item");
                });
#pragma warning restore 612, 618
        }
    }
}
